name: CI Pipeline

on:
  push:
  pull_request:
    branches:
      - "main"
    paths:
      - "**.c"
      - "**.h"
      - "**.py"
      - "**.pyx"  # Added for Cython files
      - "**.rs"   # Added for Rust files
      - "**.build"

permissions:
  contents: read

env:
  MESON_VERSION: '1.3.0'  # Set your desired Meson version
  NINJA_VERSION: '1.11.1'  # Set your desired Ninja version
  CYTHON_VERSION: '3.0.8'  # Set your desired Cython version
  BUILDDIR_NAME: 'builddir'  # Set your desired build directory version

jobs:
  host_macosx:
    strategy:
      matrix:
        os: [10.15, 11, 12, 13]  # macOS versions
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python and Tools
      run: |
          pip install meson==${MESON_VERSION} ninja==${NINJA_VERSION} cython==${CYTHON_VERSION}
    - name: Setup Build Directory
      run: |
          meson setup ${BUILDDIR_NAME}
    - name: Compile Source Code
      run: |
          meson compile -C ${BUILDDIR_NAME} -v
    - name: Test Project Code
      run: |
            meson test -C ${BUILDDIR_NAME} -v

  host_windows:
    strategy:
      matrix:
        os: ['windows-latest', 'windows-2022']
        mingw: [false, 'mingw32', 'mingw64', 'MSYS']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python and Tools
      run: |
          pip install meson==${MESON_VERSION} ninja==${NINJA_VERSION} cython==${CYTHON_VERSION}
    - name: Setup MinGW/MSYS
      if: matrix.mingw != false
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.mingw }}
        update: true
    - name: Setup Build Directory
      run: |
          meson setup ${BUILDDIR_NAME}
    - name: Compile Source Code
      run: |
          meson compile -C ${BUILDDIR_NAME} -v
    - name: Test Project Code
      run: |
            meson test -C ${BUILDDIR_NAME} -v

  host_ubuntu:
    strategy:
      matrix:
        ubuntu_version: ['latest', '22.04']
    runs-on: ubuntu-${{ matrix.ubuntu_version }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python and Tools
      run: |
          pip install meson==${MESON_VERSION} ninja==${NINJA_VERSION} cython==${CYTHON_VERSION}
          sudo apt-get install -y gcc
    - name: Setup Build Directory
      run: |
          meson setup ${BUILDDIR_NAME}
    - name: Compile Source Code
      run: |
          meson compile -C ${BUILDDIR_NAME} -v
    - name: Test Project Code
      run: |
            meson test -C ${BUILDDIR_NAME} -v
