name: Meson CI

on:
  push:
    paths:
      - "**.c"
      - "**.h"
      - "**.py"
      - "**.build"
      - "**.options"
  pull_request:
    paths:
      - "**.c"
      - "**.h"
      - "**.py"
      - "**.build"
      - "**.options"

jobs:
  build:
    name: Running on ${{ matrix.os }} with Meson v${{ matrix.meson_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2022]
        meson_version: ["1.2.0", "1.3.0", "1.4.0"] # ensure no issues cases between Meson versions
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install QUME, Meson and Ninja on Linux and MacOS
        if: runner.os != 'Windows'
        run: |
          python -m pip install --upgrade pip
          python -m pip install qume meson==${{ matrix.meson_version }} ninja

      - name: Configure
        run: meson setup builddir -Dwith_test=enabled

      - name: Compile
        run: meson compile -C builddir

      - name: Run Tests
        run: meson test -C builddir -v --test-args='--mode devops'

      - name: Upload Test Log
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: ${{ matrix.os }}_meson_testlog
          path: builddir/meson-logs/testlog.txt

  build_msvc:
    name: Running on Windows with MSVC
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install QUME, Meson and Ninja
        run: |
          python -m pip install --upgrade pip
          python -m pip install qume meson ninja
          choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended --includeOptional --passive"

      - name: Configure
        run: meson setup builddir_msvc -Dwith_test=enabled

      - name: Compile
        run: meson compile -C builddir_msvc

      - name: Run Tests
        run: meson test -C builddir_msvc -v --test-args='--mode devops'

      - name: Upload Test Log
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: windows_msvc_meson_testlog
          path: builddir_msvc/meson-logs/testlog.txt
