name: Sanity Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC

jobs:
  security_check:
    runs-on: ${{ matrix.os }}
    name: Security Check
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Meson, Ninja, and requests
        run: |
          python -m pip install meson ninja requests
      - name: Check Security
        run: python .github/tools/sanity-secure.py

  subprojects_check:
    runs-on: ${{ matrix.os }}
    name: Subprojects Check
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Meson, Ninja, and requests
        run: |
          python -m pip install meson ninja requests
      - name: Check Subprojects
        run: python .github/tools/sanity-wraps.py

  sourcecode_check:
    runs-on: ${{ matrix.os }}
    name: Source Code Check
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Meson, Ninja, and requests
        run: |
          python -m pip install meson ninja requests
      - name: Check Format
        run: python .github/tools/sanity-format.py
