name: Sanity Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  security_check:
    runs-on: ubuntu-latest
    name: Security Check
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Meson and Ninja
        run: |
          python -m pip install meson ninja
      - name: Check Security
        run: python .github/tools/sanity-secure.py

  subprojects_check:
    runs-on: ubuntu-latest
    name: Subprojects Check
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Meson and Ninja
        run: |
          python -m pip install meson ninja
      - name: Check Subprojects
        run: python .github/tools/sanity-wraps.py

  sourcecode_check:
    runs-on: ubuntu-latest
    name: Source Code Check
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Meson and Ninja
        run: |
          python -m pip install meson ninja
      - name: Check Format
        run: python .github/tools/sanity-format.py